<?php

namespace AdminBundle\Repository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    //les Classe de l'annee actuelle
    public function findClasseAnneeActuelle($id)
    {
        $qb= $this->_em->createQueryBuilder();
        $qb-> select('c')
            ->from('AdminBundle:Classe','c')
            ->leftJoin('c.Annee', 'a')
            ->Where('a.id  =  :id')
            ->setParameter('id',$id);
        return $qb->getQuery()->getResult();

    }
}
