<?php

namespace AdminBundle\Repository;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEleveSansClasse($id)
    {
        $qb= $this->_em->createQueryBuilder();
        $qb-> select('e')
            ->from('AdminBundle:Eleve','e')
            ->leftJoin('e.Classe', 'c')
            ->Where('c.id  <>  :id')
            ->setParameter('id',$id)
           ->distinct('e.id');
        return $qb->getQuery()->getResult();

    }
    //chercher les eleve sans classe
    public function findEleveSansClass()
    {
        $qb= $this->_em->createQueryBuilder();
        $qb-> select('e')
            ->from('AdminBundle:Eleve','e')
            ->leftJoin('e.Classe', 'c')
            ->Where($qb->expr()->isNull('c.id'));
        return $qb->getQuery()->getResult();

    }

    public function findEleveSansClassCetteAnnee($id)
    {
        $qb= $this->_em->createQueryBuilder();
        $qb-> select('e')
            ->from('AdminBundle:Eleve','e')
            ->leftJoin('e.Classe', 'c')
            ->leftJoin('c.Annee', 'an')
            ->Where('an.id  = :id')
            ->setParameter('id',$id)
            ;
        return $qb->getQuery()->getResult();

    }

}
